### ISSUE TITLE
Bad "main" path in package.json

### ISSUE THREAD

**Issue by gillibrand** [davidicus/use-lang-direction#10]
`package.json` uses `dist/index.js` as the `main`. That path doesn't exist in the compiled lib uploaded to npm--the two files are in the same directory. That makes it impossible to import this module with Vite, which fails on the bad path. Also, `carbon-addons-iot-react` can't be used with Vite, since is uses this a dependency.

I think the fix is as simple as just deleting the `main` property, since `index.js` is the default, which will be correct relative to where the files are copied. Another choice is to _not_ copy `package.json` into `dist` and instead upload the root directory + `dist` to npm with an appropriate ignore list to skip the uncompiled files.

**Comment by davidicus** [comment]
I published a fix for this in `v0.2.0`. You can add this in your package.json resolutions or pull in the latest PAL when the above PR is merged. Thanks For the report.

**Comment by gillibrand** [comment]
👍
